#!/bin/bash

##
## Checks that the script is running in the context of a root user.
##
check_root() {
  if [ $(id -u) -ne 0 ]; then
    >&2 echo "This script must be run as root"
    exit 1
  fi
}

##
## Checks that the script is not running in the context of a root user.
##
check_not_root() {
  if [ $(id -u) -eq 0 ]; then
    >&2 echo "This script must not be run as root"
    exit 1
  fi
}

##
## Checks that the tools listed in arguments are all installed.
##
check_tools() {
  for cmd in "$@"; do
    type -p $cmd >/dev/null || [ -x /usr/bin/$cmd ] || [ -x /bin/$cmd ] || [ -x /sbin/$cmd ] || {
      >&2 echo "The following tools must be installed..."
      >&2 echo "  $@"
      >&2 echo "  Failed to find $cmd"
      >&2 echo
      exit 1
    }
  done
}

check_tools id
